# images: php8.2-apache, mariadb, phpmyadmin
version: '3.8'
services:
  php8:
    image: php:8.2-apache
    container_name: php8
    ports:
      - "80:80"
    command: bash -c "sh /var/www/setup.sh"
    volumes:
      - ./web:/var/www/html
      - ./app:/var/www/app
      - ./assets:/var/www/html/assets
      - ./route.conf:/etc/apache2/sites-available/000-default.conf
      - ./setup.sh:/var/www/setup.sh
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_whispers
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./app/database/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    depends_on:
      - mariadb
